/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/base/BaseCheckbox.vue')['default']
    BaseCheckboxGroup: typeof import('./src/components/base/BaseCheckboxGroup.vue')['default']
    BaseForm: typeof import('./src/components/base/BaseForm.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseLink: typeof import('./src/components/base/BaseLink.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseSpinner: typeof import('./src/components/base/BaseSpinner.vue')['default']
    BaseTextarea: typeof import('./src/components/base/BaseTextarea.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    HomeBlock: typeof import('./src/components/HomeBlock.vue')['default']
    MarkdownBlock: typeof import('./src/components/MarkdownBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
